# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/sammy/Documents/project/mobilenet

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/sammy/Documents/project/mobilenet

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/sammy/Documents/project/mobilenet/CMakeFiles /mnt/c/Users/sammy/Documents/project/mobilenet//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/sammy/Documents/project/mobilenet/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named layer

# Build rule for target.
layer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 layer
.PHONY : layer

# fast build rule for target.
layer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/layer.dir/build.make CMakeFiles/layer.dir/build
.PHONY : layer/fast

#=============================================================================
# Target rules for targets named model

# Build rule for target.
model: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 model
.PHONY : model

# fast build rule for target.
model/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/model.dir/build.make CMakeFiles/model.dir/build
.PHONY : model/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

src/datahandler/datahandler.o: src/datahandler/datahandler.cpp.o
.PHONY : src/datahandler/datahandler.o

# target to build an object file
src/datahandler/datahandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/model.dir/build.make CMakeFiles/model.dir/src/datahandler/datahandler.cpp.o
.PHONY : src/datahandler/datahandler.cpp.o

src/datahandler/datahandler.i: src/datahandler/datahandler.cpp.i
.PHONY : src/datahandler/datahandler.i

# target to preprocess a source file
src/datahandler/datahandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/model.dir/build.make CMakeFiles/model.dir/src/datahandler/datahandler.cpp.i
.PHONY : src/datahandler/datahandler.cpp.i

src/datahandler/datahandler.s: src/datahandler/datahandler.cpp.s
.PHONY : src/datahandler/datahandler.s

# target to generate assembly for a file
src/datahandler/datahandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/model.dir/build.make CMakeFiles/model.dir/src/datahandler/datahandler.cpp.s
.PHONY : src/datahandler/datahandler.cpp.s

src/featuremap/featuremap.o: src/featuremap/featuremap.cpp.o
.PHONY : src/featuremap/featuremap.o

# target to build an object file
src/featuremap/featuremap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/layer.dir/build.make CMakeFiles/layer.dir/src/featuremap/featuremap.cpp.o
.PHONY : src/featuremap/featuremap.cpp.o

src/featuremap/featuremap.i: src/featuremap/featuremap.cpp.i
.PHONY : src/featuremap/featuremap.i

# target to preprocess a source file
src/featuremap/featuremap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/layer.dir/build.make CMakeFiles/layer.dir/src/featuremap/featuremap.cpp.i
.PHONY : src/featuremap/featuremap.cpp.i

src/featuremap/featuremap.s: src/featuremap/featuremap.cpp.s
.PHONY : src/featuremap/featuremap.s

# target to generate assembly for a file
src/featuremap/featuremap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/layer.dir/build.make CMakeFiles/layer.dir/src/featuremap/featuremap.cpp.s
.PHONY : src/featuremap/featuremap.cpp.s

src/layer/convolution.o: src/layer/convolution.cpp.o
.PHONY : src/layer/convolution.o

# target to build an object file
src/layer/convolution.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/layer.dir/build.make CMakeFiles/layer.dir/src/layer/convolution.cpp.o
.PHONY : src/layer/convolution.cpp.o

src/layer/convolution.i: src/layer/convolution.cpp.i
.PHONY : src/layer/convolution.i

# target to preprocess a source file
src/layer/convolution.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/layer.dir/build.make CMakeFiles/layer.dir/src/layer/convolution.cpp.i
.PHONY : src/layer/convolution.cpp.i

src/layer/convolution.s: src/layer/convolution.cpp.s
.PHONY : src/layer/convolution.s

# target to generate assembly for a file
src/layer/convolution.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/layer.dir/build.make CMakeFiles/layer.dir/src/layer/convolution.cpp.s
.PHONY : src/layer/convolution.cpp.s

src/layer/fc.o: src/layer/fc.cpp.o
.PHONY : src/layer/fc.o

# target to build an object file
src/layer/fc.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/layer.dir/build.make CMakeFiles/layer.dir/src/layer/fc.cpp.o
.PHONY : src/layer/fc.cpp.o

src/layer/fc.i: src/layer/fc.cpp.i
.PHONY : src/layer/fc.i

# target to preprocess a source file
src/layer/fc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/layer.dir/build.make CMakeFiles/layer.dir/src/layer/fc.cpp.i
.PHONY : src/layer/fc.cpp.i

src/layer/fc.s: src/layer/fc.cpp.s
.PHONY : src/layer/fc.s

# target to generate assembly for a file
src/layer/fc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/layer.dir/build.make CMakeFiles/layer.dir/src/layer/fc.cpp.s
.PHONY : src/layer/fc.cpp.s

src/layer/flatten.o: src/layer/flatten.cpp.o
.PHONY : src/layer/flatten.o

# target to build an object file
src/layer/flatten.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/layer.dir/build.make CMakeFiles/layer.dir/src/layer/flatten.cpp.o
.PHONY : src/layer/flatten.cpp.o

src/layer/flatten.i: src/layer/flatten.cpp.i
.PHONY : src/layer/flatten.i

# target to preprocess a source file
src/layer/flatten.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/layer.dir/build.make CMakeFiles/layer.dir/src/layer/flatten.cpp.i
.PHONY : src/layer/flatten.cpp.i

src/layer/flatten.s: src/layer/flatten.cpp.s
.PHONY : src/layer/flatten.s

# target to generate assembly for a file
src/layer/flatten.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/layer.dir/build.make CMakeFiles/layer.dir/src/layer/flatten.cpp.s
.PHONY : src/layer/flatten.cpp.s

src/layer/maxpooling.o: src/layer/maxpooling.cpp.o
.PHONY : src/layer/maxpooling.o

# target to build an object file
src/layer/maxpooling.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/layer.dir/build.make CMakeFiles/layer.dir/src/layer/maxpooling.cpp.o
.PHONY : src/layer/maxpooling.cpp.o

src/layer/maxpooling.i: src/layer/maxpooling.cpp.i
.PHONY : src/layer/maxpooling.i

# target to preprocess a source file
src/layer/maxpooling.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/layer.dir/build.make CMakeFiles/layer.dir/src/layer/maxpooling.cpp.i
.PHONY : src/layer/maxpooling.cpp.i

src/layer/maxpooling.s: src/layer/maxpooling.cpp.s
.PHONY : src/layer/maxpooling.s

# target to generate assembly for a file
src/layer/maxpooling.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/layer.dir/build.make CMakeFiles/layer.dir/src/layer/maxpooling.cpp.s
.PHONY : src/layer/maxpooling.cpp.s

src/layer/relu.o: src/layer/relu.cpp.o
.PHONY : src/layer/relu.o

# target to build an object file
src/layer/relu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/layer.dir/build.make CMakeFiles/layer.dir/src/layer/relu.cpp.o
.PHONY : src/layer/relu.cpp.o

src/layer/relu.i: src/layer/relu.cpp.i
.PHONY : src/layer/relu.i

# target to preprocess a source file
src/layer/relu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/layer.dir/build.make CMakeFiles/layer.dir/src/layer/relu.cpp.i
.PHONY : src/layer/relu.cpp.i

src/layer/relu.s: src/layer/relu.cpp.s
.PHONY : src/layer/relu.s

# target to generate assembly for a file
src/layer/relu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/layer.dir/build.make CMakeFiles/layer.dir/src/layer/relu.cpp.s
.PHONY : src/layer/relu.cpp.s

src/layer/softmax.o: src/layer/softmax.cpp.o
.PHONY : src/layer/softmax.o

# target to build an object file
src/layer/softmax.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/layer.dir/build.make CMakeFiles/layer.dir/src/layer/softmax.cpp.o
.PHONY : src/layer/softmax.cpp.o

src/layer/softmax.i: src/layer/softmax.cpp.i
.PHONY : src/layer/softmax.i

# target to preprocess a source file
src/layer/softmax.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/layer.dir/build.make CMakeFiles/layer.dir/src/layer/softmax.cpp.i
.PHONY : src/layer/softmax.cpp.i

src/layer/softmax.s: src/layer/softmax.cpp.s
.PHONY : src/layer/softmax.s

# target to generate assembly for a file
src/layer/softmax.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/layer.dir/build.make CMakeFiles/layer.dir/src/layer/softmax.cpp.s
.PHONY : src/layer/softmax.cpp.s

src/layer/zeropadding.o: src/layer/zeropadding.cpp.o
.PHONY : src/layer/zeropadding.o

# target to build an object file
src/layer/zeropadding.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/layer.dir/build.make CMakeFiles/layer.dir/src/layer/zeropadding.cpp.o
.PHONY : src/layer/zeropadding.cpp.o

src/layer/zeropadding.i: src/layer/zeropadding.cpp.i
.PHONY : src/layer/zeropadding.i

# target to preprocess a source file
src/layer/zeropadding.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/layer.dir/build.make CMakeFiles/layer.dir/src/layer/zeropadding.cpp.i
.PHONY : src/layer/zeropadding.cpp.i

src/layer/zeropadding.s: src/layer/zeropadding.cpp.s
.PHONY : src/layer/zeropadding.s

# target to generate assembly for a file
src/layer/zeropadding.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/layer.dir/build.make CMakeFiles/layer.dir/src/layer/zeropadding.cpp.s
.PHONY : src/layer/zeropadding.cpp.s

src/model/model.o: src/model/model.cpp.o
.PHONY : src/model/model.o

# target to build an object file
src/model/model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/model.dir/build.make CMakeFiles/model.dir/src/model/model.cpp.o
.PHONY : src/model/model.cpp.o

src/model/model.i: src/model/model.cpp.i
.PHONY : src/model/model.i

# target to preprocess a source file
src/model/model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/model.dir/build.make CMakeFiles/model.dir/src/model/model.cpp.i
.PHONY : src/model/model.cpp.i

src/model/model.s: src/model/model.cpp.s
.PHONY : src/model/model.s

# target to generate assembly for a file
src/model/model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/model.dir/build.make CMakeFiles/model.dir/src/model/model.cpp.s
.PHONY : src/model/model.cpp.s

src/test.o: src/test.cpp.o
.PHONY : src/test.o

# target to build an object file
src/test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/test.cpp.o
.PHONY : src/test.cpp.o

src/test.i: src/test.cpp.i
.PHONY : src/test.i

# target to preprocess a source file
src/test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/test.cpp.i
.PHONY : src/test.cpp.i

src/test.s: src/test.cpp.s
.PHONY : src/test.s

# target to generate assembly for a file
src/test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/test.cpp.s
.PHONY : src/test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... layer"
	@echo "... model"
	@echo "... test"
	@echo "... src/datahandler/datahandler.o"
	@echo "... src/datahandler/datahandler.i"
	@echo "... src/datahandler/datahandler.s"
	@echo "... src/featuremap/featuremap.o"
	@echo "... src/featuremap/featuremap.i"
	@echo "... src/featuremap/featuremap.s"
	@echo "... src/layer/convolution.o"
	@echo "... src/layer/convolution.i"
	@echo "... src/layer/convolution.s"
	@echo "... src/layer/fc.o"
	@echo "... src/layer/fc.i"
	@echo "... src/layer/fc.s"
	@echo "... src/layer/flatten.o"
	@echo "... src/layer/flatten.i"
	@echo "... src/layer/flatten.s"
	@echo "... src/layer/maxpooling.o"
	@echo "... src/layer/maxpooling.i"
	@echo "... src/layer/maxpooling.s"
	@echo "... src/layer/relu.o"
	@echo "... src/layer/relu.i"
	@echo "... src/layer/relu.s"
	@echo "... src/layer/softmax.o"
	@echo "... src/layer/softmax.i"
	@echo "... src/layer/softmax.s"
	@echo "... src/layer/zeropadding.o"
	@echo "... src/layer/zeropadding.i"
	@echo "... src/layer/zeropadding.s"
	@echo "... src/model/model.o"
	@echo "... src/model/model.i"
	@echo "... src/model/model.s"
	@echo "... src/test.o"
	@echo "... src/test.i"
	@echo "... src/test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

