# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/MICS/Desktop/proj/SSD

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/MICS/Desktop/proj/SSD

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/MICS/Desktop/proj/SSD/CMakeFiles /mnt/c/Users/MICS/Desktop/proj/SSD//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/MICS/Desktop/proj/SSD/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tensor

# Build rule for target.
tensor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tensor
.PHONY : tensor

# fast build rule for target.
tensor/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tensor.dir/build.make CMakeFiles/tensor.dir/build
.PHONY : tensor/fast

#=============================================================================
# Target rules for targets named layer

# Build rule for target.
layer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 layer
.PHONY : layer

# fast build rule for target.
layer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/layer.dir/build.make CMakeFiles/layer.dir/build
.PHONY : layer/fast

#=============================================================================
# Target rules for targets named datahandler

# Build rule for target.
datahandler: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 datahandler
.PHONY : datahandler

# fast build rule for target.
datahandler/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/datahandler.dir/build.make CMakeFiles/datahandler.dir/build
.PHONY : datahandler/fast

#=============================================================================
# Target rules for targets named model

# Build rule for target.
model: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 model
.PHONY : model

# fast build rule for target.
model/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/model.dir/build.make CMakeFiles/model.dir/build
.PHONY : model/fast

#=============================================================================
# Target rules for targets named test_conv

# Build rule for target.
test_conv: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_conv
.PHONY : test_conv

# fast build rule for target.
test_conv/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_conv.dir/build.make CMakeFiles/test_conv.dir/build
.PHONY : test_conv/fast

#=============================================================================
# Target rules for targets named test_img

# Build rule for target.
test_img: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_img
.PHONY : test_img

# fast build rule for target.
test_img/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_img.dir/build.make CMakeFiles/test_img.dir/build
.PHONY : test_img/fast

#=============================================================================
# Target rules for targets named test_maxpool

# Build rule for target.
test_maxpool: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_maxpool
.PHONY : test_maxpool

# fast build rule for target.
test_maxpool/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_maxpool.dir/build.make CMakeFiles/test_maxpool.dir/build
.PHONY : test_maxpool/fast

#=============================================================================
# Target rules for targets named test_model

# Build rule for target.
test_model: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_model
.PHONY : test_model

# fast build rule for target.
test_model/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_model.dir/build.make CMakeFiles/test_model.dir/build
.PHONY : test_model/fast

#=============================================================================
# Target rules for targets named test_param

# Build rule for target.
test_param: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_param
.PHONY : test_param

# fast build rule for target.
test_param/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_param.dir/build.make CMakeFiles/test_param.dir/build
.PHONY : test_param/fast

#=============================================================================
# Target rules for targets named test_zeropadd

# Build rule for target.
test_zeropadd: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_zeropadd
.PHONY : test_zeropadd

# fast build rule for target.
test_zeropadd/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_zeropadd.dir/build.make CMakeFiles/test_zeropadd.dir/build
.PHONY : test_zeropadd/fast

src/datahandler/datahandler.o: src/datahandler/datahandler.c.o
.PHONY : src/datahandler/datahandler.o

# target to build an object file
src/datahandler/datahandler.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/datahandler.dir/build.make CMakeFiles/datahandler.dir/src/datahandler/datahandler.c.o
.PHONY : src/datahandler/datahandler.c.o

src/datahandler/datahandler.i: src/datahandler/datahandler.c.i
.PHONY : src/datahandler/datahandler.i

# target to preprocess a source file
src/datahandler/datahandler.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/datahandler.dir/build.make CMakeFiles/datahandler.dir/src/datahandler/datahandler.c.i
.PHONY : src/datahandler/datahandler.c.i

src/datahandler/datahandler.s: src/datahandler/datahandler.c.s
.PHONY : src/datahandler/datahandler.s

# target to generate assembly for a file
src/datahandler/datahandler.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/datahandler.dir/build.make CMakeFiles/datahandler.dir/src/datahandler/datahandler.c.s
.PHONY : src/datahandler/datahandler.c.s

src/layer/conv_layer.o: src/layer/conv_layer.c.o
.PHONY : src/layer/conv_layer.o

# target to build an object file
src/layer/conv_layer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/layer.dir/build.make CMakeFiles/layer.dir/src/layer/conv_layer.c.o
.PHONY : src/layer/conv_layer.c.o

src/layer/conv_layer.i: src/layer/conv_layer.c.i
.PHONY : src/layer/conv_layer.i

# target to preprocess a source file
src/layer/conv_layer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/layer.dir/build.make CMakeFiles/layer.dir/src/layer/conv_layer.c.i
.PHONY : src/layer/conv_layer.c.i

src/layer/conv_layer.s: src/layer/conv_layer.c.s
.PHONY : src/layer/conv_layer.s

# target to generate assembly for a file
src/layer/conv_layer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/layer.dir/build.make CMakeFiles/layer.dir/src/layer/conv_layer.c.s
.PHONY : src/layer/conv_layer.c.s

src/layer/maxpool_layer.o: src/layer/maxpool_layer.c.o
.PHONY : src/layer/maxpool_layer.o

# target to build an object file
src/layer/maxpool_layer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/layer.dir/build.make CMakeFiles/layer.dir/src/layer/maxpool_layer.c.o
.PHONY : src/layer/maxpool_layer.c.o

src/layer/maxpool_layer.i: src/layer/maxpool_layer.c.i
.PHONY : src/layer/maxpool_layer.i

# target to preprocess a source file
src/layer/maxpool_layer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/layer.dir/build.make CMakeFiles/layer.dir/src/layer/maxpool_layer.c.i
.PHONY : src/layer/maxpool_layer.c.i

src/layer/maxpool_layer.s: src/layer/maxpool_layer.c.s
.PHONY : src/layer/maxpool_layer.s

# target to generate assembly for a file
src/layer/maxpool_layer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/layer.dir/build.make CMakeFiles/layer.dir/src/layer/maxpool_layer.c.s
.PHONY : src/layer/maxpool_layer.c.s

src/layer/zeropadd_layer.o: src/layer/zeropadd_layer.c.o
.PHONY : src/layer/zeropadd_layer.o

# target to build an object file
src/layer/zeropadd_layer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/layer.dir/build.make CMakeFiles/layer.dir/src/layer/zeropadd_layer.c.o
.PHONY : src/layer/zeropadd_layer.c.o

src/layer/zeropadd_layer.i: src/layer/zeropadd_layer.c.i
.PHONY : src/layer/zeropadd_layer.i

# target to preprocess a source file
src/layer/zeropadd_layer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/layer.dir/build.make CMakeFiles/layer.dir/src/layer/zeropadd_layer.c.i
.PHONY : src/layer/zeropadd_layer.c.i

src/layer/zeropadd_layer.s: src/layer/zeropadd_layer.c.s
.PHONY : src/layer/zeropadd_layer.s

# target to generate assembly for a file
src/layer/zeropadd_layer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/layer.dir/build.make CMakeFiles/layer.dir/src/layer/zeropadd_layer.c.s
.PHONY : src/layer/zeropadd_layer.c.s

src/model/auxiliary.o: src/model/auxiliary.c.o
.PHONY : src/model/auxiliary.o

# target to build an object file
src/model/auxiliary.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/model.dir/build.make CMakeFiles/model.dir/src/model/auxiliary.c.o
.PHONY : src/model/auxiliary.c.o

src/model/auxiliary.i: src/model/auxiliary.c.i
.PHONY : src/model/auxiliary.i

# target to preprocess a source file
src/model/auxiliary.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/model.dir/build.make CMakeFiles/model.dir/src/model/auxiliary.c.i
.PHONY : src/model/auxiliary.c.i

src/model/auxiliary.s: src/model/auxiliary.c.s
.PHONY : src/model/auxiliary.s

# target to generate assembly for a file
src/model/auxiliary.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/model.dir/build.make CMakeFiles/model.dir/src/model/auxiliary.c.s
.PHONY : src/model/auxiliary.c.s

src/model/predict.o: src/model/predict.c.o
.PHONY : src/model/predict.o

# target to build an object file
src/model/predict.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/model.dir/build.make CMakeFiles/model.dir/src/model/predict.c.o
.PHONY : src/model/predict.c.o

src/model/predict.i: src/model/predict.c.i
.PHONY : src/model/predict.i

# target to preprocess a source file
src/model/predict.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/model.dir/build.make CMakeFiles/model.dir/src/model/predict.c.i
.PHONY : src/model/predict.c.i

src/model/predict.s: src/model/predict.c.s
.PHONY : src/model/predict.s

# target to generate assembly for a file
src/model/predict.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/model.dir/build.make CMakeFiles/model.dir/src/model/predict.c.s
.PHONY : src/model/predict.c.s

src/model/ssd.o: src/model/ssd.c.o
.PHONY : src/model/ssd.o

# target to build an object file
src/model/ssd.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/model.dir/build.make CMakeFiles/model.dir/src/model/ssd.c.o
.PHONY : src/model/ssd.c.o

src/model/ssd.i: src/model/ssd.c.i
.PHONY : src/model/ssd.i

# target to preprocess a source file
src/model/ssd.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/model.dir/build.make CMakeFiles/model.dir/src/model/ssd.c.i
.PHONY : src/model/ssd.c.i

src/model/ssd.s: src/model/ssd.c.s
.PHONY : src/model/ssd.s

# target to generate assembly for a file
src/model/ssd.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/model.dir/build.make CMakeFiles/model.dir/src/model/ssd.c.s
.PHONY : src/model/ssd.c.s

src/model/vgg.o: src/model/vgg.c.o
.PHONY : src/model/vgg.o

# target to build an object file
src/model/vgg.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/model.dir/build.make CMakeFiles/model.dir/src/model/vgg.c.o
.PHONY : src/model/vgg.c.o

src/model/vgg.i: src/model/vgg.c.i
.PHONY : src/model/vgg.i

# target to preprocess a source file
src/model/vgg.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/model.dir/build.make CMakeFiles/model.dir/src/model/vgg.c.i
.PHONY : src/model/vgg.c.i

src/model/vgg.s: src/model/vgg.c.s
.PHONY : src/model/vgg.s

# target to generate assembly for a file
src/model/vgg.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/model.dir/build.make CMakeFiles/model.dir/src/model/vgg.c.s
.PHONY : src/model/vgg.c.s

src/tensor/tensor.o: src/tensor/tensor.c.o
.PHONY : src/tensor/tensor.o

# target to build an object file
src/tensor/tensor.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tensor.dir/build.make CMakeFiles/tensor.dir/src/tensor/tensor.c.o
.PHONY : src/tensor/tensor.c.o

src/tensor/tensor.i: src/tensor/tensor.c.i
.PHONY : src/tensor/tensor.i

# target to preprocess a source file
src/tensor/tensor.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tensor.dir/build.make CMakeFiles/tensor.dir/src/tensor/tensor.c.i
.PHONY : src/tensor/tensor.c.i

src/tensor/tensor.s: src/tensor/tensor.c.s
.PHONY : src/tensor/tensor.s

# target to generate assembly for a file
src/tensor/tensor.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tensor.dir/build.make CMakeFiles/tensor.dir/src/tensor/tensor.c.s
.PHONY : src/tensor/tensor.c.s

test/test_conv.o: test/test_conv.c.o
.PHONY : test/test_conv.o

# target to build an object file
test/test_conv.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_conv.dir/build.make CMakeFiles/test_conv.dir/test/test_conv.c.o
.PHONY : test/test_conv.c.o

test/test_conv.i: test/test_conv.c.i
.PHONY : test/test_conv.i

# target to preprocess a source file
test/test_conv.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_conv.dir/build.make CMakeFiles/test_conv.dir/test/test_conv.c.i
.PHONY : test/test_conv.c.i

test/test_conv.s: test/test_conv.c.s
.PHONY : test/test_conv.s

# target to generate assembly for a file
test/test_conv.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_conv.dir/build.make CMakeFiles/test_conv.dir/test/test_conv.c.s
.PHONY : test/test_conv.c.s

test/test_img.o: test/test_img.c.o
.PHONY : test/test_img.o

# target to build an object file
test/test_img.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_img.dir/build.make CMakeFiles/test_img.dir/test/test_img.c.o
.PHONY : test/test_img.c.o

test/test_img.i: test/test_img.c.i
.PHONY : test/test_img.i

# target to preprocess a source file
test/test_img.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_img.dir/build.make CMakeFiles/test_img.dir/test/test_img.c.i
.PHONY : test/test_img.c.i

test/test_img.s: test/test_img.c.s
.PHONY : test/test_img.s

# target to generate assembly for a file
test/test_img.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_img.dir/build.make CMakeFiles/test_img.dir/test/test_img.c.s
.PHONY : test/test_img.c.s

test/test_maxpool.o: test/test_maxpool.c.o
.PHONY : test/test_maxpool.o

# target to build an object file
test/test_maxpool.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_maxpool.dir/build.make CMakeFiles/test_maxpool.dir/test/test_maxpool.c.o
.PHONY : test/test_maxpool.c.o

test/test_maxpool.i: test/test_maxpool.c.i
.PHONY : test/test_maxpool.i

# target to preprocess a source file
test/test_maxpool.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_maxpool.dir/build.make CMakeFiles/test_maxpool.dir/test/test_maxpool.c.i
.PHONY : test/test_maxpool.c.i

test/test_maxpool.s: test/test_maxpool.c.s
.PHONY : test/test_maxpool.s

# target to generate assembly for a file
test/test_maxpool.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_maxpool.dir/build.make CMakeFiles/test_maxpool.dir/test/test_maxpool.c.s
.PHONY : test/test_maxpool.c.s

test/test_model.o: test/test_model.c.o
.PHONY : test/test_model.o

# target to build an object file
test/test_model.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_model.dir/build.make CMakeFiles/test_model.dir/test/test_model.c.o
.PHONY : test/test_model.c.o

test/test_model.i: test/test_model.c.i
.PHONY : test/test_model.i

# target to preprocess a source file
test/test_model.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_model.dir/build.make CMakeFiles/test_model.dir/test/test_model.c.i
.PHONY : test/test_model.c.i

test/test_model.s: test/test_model.c.s
.PHONY : test/test_model.s

# target to generate assembly for a file
test/test_model.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_model.dir/build.make CMakeFiles/test_model.dir/test/test_model.c.s
.PHONY : test/test_model.c.s

test/test_param.o: test/test_param.c.o
.PHONY : test/test_param.o

# target to build an object file
test/test_param.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_param.dir/build.make CMakeFiles/test_param.dir/test/test_param.c.o
.PHONY : test/test_param.c.o

test/test_param.i: test/test_param.c.i
.PHONY : test/test_param.i

# target to preprocess a source file
test/test_param.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_param.dir/build.make CMakeFiles/test_param.dir/test/test_param.c.i
.PHONY : test/test_param.c.i

test/test_param.s: test/test_param.c.s
.PHONY : test/test_param.s

# target to generate assembly for a file
test/test_param.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_param.dir/build.make CMakeFiles/test_param.dir/test/test_param.c.s
.PHONY : test/test_param.c.s

test/test_zeropadd.o: test/test_zeropadd.c.o
.PHONY : test/test_zeropadd.o

# target to build an object file
test/test_zeropadd.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_zeropadd.dir/build.make CMakeFiles/test_zeropadd.dir/test/test_zeropadd.c.o
.PHONY : test/test_zeropadd.c.o

test/test_zeropadd.i: test/test_zeropadd.c.i
.PHONY : test/test_zeropadd.i

# target to preprocess a source file
test/test_zeropadd.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_zeropadd.dir/build.make CMakeFiles/test_zeropadd.dir/test/test_zeropadd.c.i
.PHONY : test/test_zeropadd.c.i

test/test_zeropadd.s: test/test_zeropadd.c.s
.PHONY : test/test_zeropadd.s

# target to generate assembly for a file
test/test_zeropadd.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_zeropadd.dir/build.make CMakeFiles/test_zeropadd.dir/test/test_zeropadd.c.s
.PHONY : test/test_zeropadd.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... datahandler"
	@echo "... layer"
	@echo "... model"
	@echo "... tensor"
	@echo "... test_conv"
	@echo "... test_img"
	@echo "... test_maxpool"
	@echo "... test_model"
	@echo "... test_param"
	@echo "... test_zeropadd"
	@echo "... src/datahandler/datahandler.o"
	@echo "... src/datahandler/datahandler.i"
	@echo "... src/datahandler/datahandler.s"
	@echo "... src/layer/conv_layer.o"
	@echo "... src/layer/conv_layer.i"
	@echo "... src/layer/conv_layer.s"
	@echo "... src/layer/maxpool_layer.o"
	@echo "... src/layer/maxpool_layer.i"
	@echo "... src/layer/maxpool_layer.s"
	@echo "... src/layer/zeropadd_layer.o"
	@echo "... src/layer/zeropadd_layer.i"
	@echo "... src/layer/zeropadd_layer.s"
	@echo "... src/model/auxiliary.o"
	@echo "... src/model/auxiliary.i"
	@echo "... src/model/auxiliary.s"
	@echo "... src/model/predict.o"
	@echo "... src/model/predict.i"
	@echo "... src/model/predict.s"
	@echo "... src/model/ssd.o"
	@echo "... src/model/ssd.i"
	@echo "... src/model/ssd.s"
	@echo "... src/model/vgg.o"
	@echo "... src/model/vgg.i"
	@echo "... src/model/vgg.s"
	@echo "... src/tensor/tensor.o"
	@echo "... src/tensor/tensor.i"
	@echo "... src/tensor/tensor.s"
	@echo "... test/test_conv.o"
	@echo "... test/test_conv.i"
	@echo "... test/test_conv.s"
	@echo "... test/test_img.o"
	@echo "... test/test_img.i"
	@echo "... test/test_img.s"
	@echo "... test/test_maxpool.o"
	@echo "... test/test_maxpool.i"
	@echo "... test/test_maxpool.s"
	@echo "... test/test_model.o"
	@echo "... test/test_model.i"
	@echo "... test/test_model.s"
	@echo "... test/test_param.o"
	@echo "... test/test_param.i"
	@echo "... test/test_param.s"
	@echo "... test/test_zeropadd.o"
	@echo "... test/test_zeropadd.i"
	@echo "... test/test_zeropadd.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

